#set_property IOSTANDARD LVCMOS33 [get_ports {count[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {count[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {count[0]}]
#set_property IOSTANDARD LVCMOS33 [get_ports clk]
#set_property IOSTANDARD LVCMOS33 [get_ports four_count]
#set_property IOSTANDARD LVCMOS33 [get_ports input_val]
#set_property PACKAGE_PIN P17 [get_ports clk]
#set_property PACKAGE_PIN H17 [get_ports four_count]
#set_property PACKAGE_PIN J15 [get_ports input_val]
#set_property PACKAGE_PIN N14 [get_ports {count[2]}]
#set_property PACKAGE_PIN J13 [get_ports {count[1]}]
#set_property PACKAGE_PIN K15 [get_ports {count[0]}]

set_property -dict { PACKAGE_PIN E3    IOSTANDARD LVCMOS33 } [get_ports { CLK100MHZ }]; #IO_L12P_T1_MRCC_35 Sch=clk100mhz
create_clock -add -name sys_clk_pin -period 10.00 -waveform {0 5} [get_ports {CLK100MHZ}];

#set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment[6]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment[5]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment[4]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment[3]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment[2]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment[1]}]
#set_property IOSTANDARD LVCMOS33 [get_ports {seven_segment[0]}]
#set_property PACKAGE_PIN L18 [get_ports {seven_segment[0]}]
#set_property PACKAGE_PIN T11 [get_ports {seven_segment[1]}]
#set_property PACKAGE_PIN P15 [get_ports {seven_segment[2]}]
#set_property PACKAGE_PIN K13 [get_ports {seven_segment[3]}]
#set_property PACKAGE_PIN K16 [get_ports {seven_segment[4]}]
#set_property PACKAGE_PIN R10 [get_ports {seven_segment[5]}]
#set_property PACKAGE_PIN T10 [get_ports {seven_segment[6]}]

set_property -dict { PACKAGE_PIN D14   IOSTANDARD LVCMOS33 } [get_ports { clk_out }]; #IO_L1P_T0_AD0P_15 Sch=jb[1]
set_property -dict { PACKAGE_PIN F16   IOSTANDARD LVCMOS33 } [get_ports { new_address[0] }]; #IO_L14N_T2_SRCC_15 Sch=jb[2]
set_property -dict { PACKAGE_PIN G16   IOSTANDARD LVCMOS33 } [get_ports { new_address[1] }]; #IO_L13N_T2_MRCC_15 Sch=jb[3]
set_property -dict { PACKAGE_PIN H14   IOSTANDARD LVCMOS33 } [get_ports { new_address[2] }]; #IO_L15P_T2_DQS_15 Sch=jb[4]
set_property -dict { PACKAGE_PIN E16   IOSTANDARD LVCMOS33 } [get_ports { start_out }]; #IO_L11N_T1_SRCC_15 Sch=jb[7]

set_property -dict { PACKAGE_PIN V11   IOSTANDARD LVCMOS33 } [get_ports { move_goalie }]; #IO_L22N_T3_A04_D20_14 Sch=led[13]
set_property -dict { PACKAGE_PIN V12   IOSTANDARD LVCMOS33 } [get_ports { min_address[0] }]; #IO_L20N_T3_A07_D23_14 Sch=led[14]
set_property -dict { PACKAGE_PIN V14   IOSTANDARD LVCMOS33 } [get_ports { min_address[1] }]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]
set_property -dict { PACKAGE_PIN V15   IOSTANDARD LVCMOS33 } [get_ports { min_address[2] }]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]

set_property -dict { PACKAGE_PIN T16   IOSTANDARD LVCMOS33 } [get_ports { transistor_count[0] }]; #IO_L20N_T3_A07_D23_14 Sch=led[14]
set_property -dict { PACKAGE_PIN U14   IOSTANDARD LVCMOS33 } [get_ports { transistor_count[1] }]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]
set_property -dict { PACKAGE_PIN T15   IOSTANDARD LVCMOS33 } [get_ports { transistor_count[2] }]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]
set_property -dict { PACKAGE_PIN V16   IOSTANDARD LVCMOS33 } [get_ports { output_temp[7]}]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]
set_property -dict { PACKAGE_PIN U16   IOSTANDARD LVCMOS33 } [get_ports { output_temp[6]}]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]
set_property -dict { PACKAGE_PIN U17   IOSTANDARD LVCMOS33 } [get_ports { output_temp[5]}]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]
set_property -dict { PACKAGE_PIN V17   IOSTANDARD LVCMOS33 } [get_ports { output_temp[4]}]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]
set_property -dict { PACKAGE_PIN R18   IOSTANDARD LVCMOS33 } [get_ports { output_temp[3]}]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]
set_property -dict { PACKAGE_PIN N14   IOSTANDARD LVCMOS33 } [get_ports { output_temp[2]}]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]
set_property -dict { PACKAGE_PIN J13   IOSTANDARD LVCMOS33 } [get_ports { output_temp[1]}]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]
set_property -dict { PACKAGE_PIN K15   IOSTANDARD LVCMOS33 } [get_ports { output_temp[0]}]; #IO_L21N_T3_DQS_A06_D22_14 Sch=led[15]

#set_property -dict { PACKAGE_PIN E16   IOSTANDARD LVCMOS33 } [get_ports { seven_segment[4] }]; #IO_L11N_T1_SRCC_15 Sch=jb[7]
#set_property -dict { PACKAGE_PIN F13   IOSTANDARD LVCMOS33 } [get_ports { seven_segment[5] }]; #IO_L5P_T0_AD9P_15 Sch=jb[8]
#set_property -dict { PACKAGE_PIN G13   IOSTANDARD LVCMOS33 } [get_ports { seven_segment[6] }]; #IO_0_15 Sch=jb[9]
#set_property -dict { PACKAGE_PIN H16   IOSTANDARD LVCMOS33 } [get_ports { JB[10] }]; #IO_L13P_T2_MRCC_15 Sch=jb[10]


set_property -dict { PACKAGE_PIN C17   IOSTANDARD LVCMOS33 } [get_ports { analog_input[7] }]; #IO_L20N_T3_A19_15 Sch=ja[1]
set_property -dict { PACKAGE_PIN D18   IOSTANDARD LVCMOS33 } [get_ports { analog_input[6] }]; #IO_L21N_T3_DQS_A18_15 Sch=ja[2]
set_property -dict { PACKAGE_PIN E18   IOSTANDARD LVCMOS33 } [get_ports { analog_input[5] }]; #IO_L21P_T3_DQS_15 Sch=ja[3]
set_property -dict { PACKAGE_PIN G17   IOSTANDARD LVCMOS33 } [get_ports { analog_input[4] }]; #IO_L18N_T2_A23_15 Sch=ja[4]
set_property -dict { PACKAGE_PIN D17   IOSTANDARD LVCMOS33 } [get_ports { analog_input[3] }]; #IO_L16N_T2_A27_15 Sch=ja[7]
set_property -dict { PACKAGE_PIN E17   IOSTANDARD LVCMOS33 } [get_ports { analog_input[2] }]; #IO_L16P_T2_A28_15 Sch=ja[8]
set_property -dict { PACKAGE_PIN F18   IOSTANDARD LVCMOS33 } [get_ports { analog_input[1] }]; #IO_L22N_T3_A16_15 Sch=ja[9]
set_property -dict { PACKAGE_PIN G18   IOSTANDARD LVCMOS33 } [get_ports { analog_input[0] }]; #IO_L22P_T3_A17_15 Sch=ja[10]
