# 
# Synthesis run script generated by Vivado
# 

set TIME_start [clock seconds] 
namespace eval ::optrace {
  variable script "C:/Users/taf27/Documents/350-Project/350-Project/350-Project.runs/synth_1/Wrapper.tcl"
  variable category "vivado_synth"
}

# Try to connect to running dispatch if we haven't done so already.
# This code assumes that the Tcl interpreter is not using threads,
# since the ::dispatch::connected variable isn't mutex protected.
if {![info exists ::dispatch::connected]} {
  namespace eval ::dispatch {
    variable connected false
    if {[llength [array get env XILINX_CD_CONNECT_ID]] > 0} {
      set result "true"
      if {[catch {
        if {[lsearch -exact [package names] DispatchTcl] < 0} {
          set result [load librdi_cd_clienttcl[info sharedlibextension]] 
        }
        if {$result eq "false"} {
          puts "WARNING: Could not load dispatch client library"
        }
        set connect_id [ ::dispatch::init_client -mode EXISTING_SERVER ]
        if { $connect_id eq "" } {
          puts "WARNING: Could not initialize dispatch client"
        } else {
          puts "INFO: Dispatch client connection id - $connect_id"
          set connected true
        }
      } catch_res]} {
        puts "WARNING: failed to connect to dispatch server - $catch_res"
      }
    }
  }
}
if {$::dispatch::connected} {
  # Remove the dummy proc if it exists.
  if { [expr {[llength [info procs ::OPTRACE]] > 0}] } {
    rename ::OPTRACE ""
  }
  proc ::OPTRACE { task action {tags {} } } {
    ::vitis_log::op_trace "$task" $action -tags $tags -script $::optrace::script -category $::optrace::category
  }
  # dispatch is generic. We specifically want to attach logging.
  ::vitis_log::connect_client
} else {
  # Add dummy proc if it doesn't exist.
  if { [expr {[llength [info procs ::OPTRACE]] == 0}] } {
    proc ::OPTRACE {{arg1 \"\" } {arg2 \"\"} {arg3 \"\" } {arg4 \"\"} {arg5 \"\" } {arg6 \"\"}} {
        # Do nothing
    }
  }
}

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
OPTRACE "synth_1" START { ROLLUP_AUTO }
set_param chipscope.maxJobs 3
set_param xicom.use_bs_reader 1
set_msg_config -id {HDL 9-1061} -limit 100000
set_msg_config -id {HDL 9-1654} -limit 100000
OPTRACE "Creating in-memory project" START { }
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_property webtalk.parent_dir C:/Users/taf27/Documents/350-Project/350-Project/350-Project.cache/wt [current_project]
set_property parent.project_path C:/Users/taf27/Documents/350-Project/350-Project/350-Project.xpr [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language Verilog [current_project]
set_property ip_output_repo c:/Users/taf27/Documents/350-Project/350-Project/350-Project.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
OPTRACE "Creating in-memory project" END { }
OPTRACE "Adding files" START { }
read_mem {
  C:/Users/taf27/Documents/350-Project/arithmetic.mem
  C:/Users/taf27/Documents/350-Project/assembler/stepper.mem
}
read_verilog -library xil_defaultlib {
  C:/Users/taf27/Documents/350-Project/utilities/And_32.v
  C:/Users/taf27/Documents/350-Project/utilities/CLA_16.v
  C:/Users/taf27/Documents/350-Project/utilities/CLA_32.v
  C:/Users/taf27/Documents/350-Project/utilities/CLA_8.v
  C:/Users/taf27/Documents/350-Project/IO.v
  C:/Users/taf27/Documents/350-Project/utilities/LeftShift.v
  C:/Users/taf27/Documents/350-Project/utilities/Or_32.v
  C:/Users/taf27/Documents/350-Project/RAM.v
  C:/Users/taf27/Documents/350-Project/ROM.v
  C:/Users/taf27/Documents/350-Project/utilities/RightShift.v
  C:/Users/taf27/Documents/350-Project/adc_phototransistor.v
  C:/Users/taf27/Documents/350-Project/alu.v
  C:/Users/taf27/Documents/350-Project/utilities/counter_32.v
  C:/Users/taf27/Documents/350-Project/decoder3to8.v
  C:/Users/taf27/Documents/350-Project/utilities/decoder_32.v
  C:/Users/taf27/Documents/350-Project/utilities/dffe_ref.v
  C:/Users/taf27/Documents/350-Project/utilities/dffe_ref_falling.v
  C:/Users/taf27/Documents/350-Project/divider.v
  C:/Users/taf27/Documents/350-Project/latches/dx_latch.v
  C:/Users/taf27/Documents/350-Project/latches/fd_latch.v
  C:/Users/taf27/Documents/350-Project/multdiv.v
  C:/Users/taf27/Documents/350-Project/multiplier.v
  C:/Users/taf27/Documents/350-Project/utilities/mux_2.v
  C:/Users/taf27/Documents/350-Project/utilities/mux_2_1.v
  C:/Users/taf27/Documents/350-Project/utilities/mux_32.v
  C:/Users/taf27/Documents/350-Project/utilities/mux_4.v
  C:/Users/taf27/Documents/350-Project/utilities/mux_8.v
  C:/Users/taf27/Documents/350-Project/latches/mw_latch.v
  C:/Users/taf27/Documents/350-Project/latches/pc_latch.v
  C:/Users/taf27/Documents/350-Project/processor.v
  C:/Users/taf27/Documents/350-Project/latches/pw_latch.v
  C:/Users/taf27/Documents/350-Project/utilities/reg_32.v
  C:/Users/taf27/Documents/350-Project/utilities/reg_64.v
  C:/Users/taf27/Documents/350-Project/utilities/reg_65.v
  C:/Users/taf27/Documents/350-Project/regfile.v
  C:/Users/taf27/Documents/350-Project/stepper.v
  C:/Users/taf27/Documents/350-Project/utilities/tffe_ref.v
  C:/Users/taf27/Documents/350-Project/utilities/tristate.v
  C:/Users/taf27/Documents/350-Project/utilities/twos_complement.v
  C:/Users/taf27/Documents/350-Project/latches/xm_latch.v
  C:/Users/taf27/Documents/350-Project/Wrapper.v
  C:/Users/taf27/Documents/350-Project/utilities/Nand_32.v
  C:/Users/taf27/Documents/350-Project/Wrapper_tb.v
  C:/Users/taf27/Documents/350-Project/utilities/And_8.v
  C:/Users/taf27/Documents/350-Project/utilities/FullAdder.v
  C:/Users/taf27/Documents/350-Project/utilities/Or_8.v
}
OPTRACE "Adding files" END { }
# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/taf27/Documents/350-Project/350-Project/350-Project.srcs/constrs_1/new/master.xdc
set_property used_in_implementation false [get_files C:/Users/taf27/Documents/350-Project/350-Project/350-Project.srcs/constrs_1/new/master.xdc]

set_param ips.enableIPCacheLiteLoad 1
close [open __synthesis_is_running__ w]

OPTRACE "synth_design" START { }
synth_design -top Wrapper -part xc7a100tcsg324-1
OPTRACE "synth_design" END { }
if { [get_msg_config -count -severity {CRITICAL WARNING}] > 0 } {
 send_msg_id runtcl-6 info "Synthesis results are not added to the cache due to CRITICAL_WARNING"
}


OPTRACE "write_checkpoint" START { CHECKPOINT }
# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef Wrapper.dcp
OPTRACE "write_checkpoint" END { }
OPTRACE "synth reports" START { REPORT }
create_report "synth_1_synth_report_utilization_0" "report_utilization -file Wrapper_utilization_synth.rpt -pb Wrapper_utilization_synth.pb"
OPTRACE "synth reports" END { }
file delete __synthesis_is_running__
close [open __synthesis_is_complete__ w]
OPTRACE "synth_1" END { }
